name = "XAIBase"
uuid = "9b48221d-a747-4c1b-9860-46a1d8ba24a7"
authors = ["Adrian Hill <gh@adrianhill.de>"]
version = "1.1.1"

[deps]
TextHeatmaps = "2dd6718a-6083-4824-b9f7-90e4a57f72d2"
VisionHeatmaps = "27106da1-f8bc-4ca8-8c66-9b8289f1e035"

[compat]
TextHeatmaps = "1.1"
VisionHeatmaps = "1.1"
julia = "1.6"
