name = "XAIBase"
uuid = "9b48221d-a747-4c1b-9860-46a1d8ba24a7"
authors = ["Adrian Hill <gh@adrianhill.de>"]
version = "1.0.0"

[deps]
TextHeatmaps = "2dd6718a-6083-4824-b9f7-90e4a57f72d2"

[weakdeps]
TextHeatmaps = "2dd6718a-6083-4824-b9f7-90e4a57f72d2"

[extensions]
XAITextHeatmapsExt = "TextHeatmaps"

[compat]
TextHeatmaps = "1.1"
julia = "1.6"
